spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwtappdb?serverTimezone=UTC
    username: root
    password: admin
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:mysql://localhost:3306/jwtappdb?serverTimezone=UTC
    user: root
    password: admin
jwt:
  token:
    secret: jwtapp
    expired: 3600000

